### ISSUE TITLE
[Question] binxio/cfn-resource-provider vs aws-cloudformation/custom-resource-helper

### ISSUE THREAD

**Issue by LaikaN57** [binxio/cfn-resource-provider#12]
I am wondering if this project has purpose now that https://github.com/aws-cloudformation/custom-resource-helper exists? Should we just fold in the features from this repo into custom-resource-helper, add a deprecation warning, and start supporting efforts on a "blessed" repo?

While I highly appreciate the authors of this repo for supporting us while we did not have the AWS version, I think it would be helpful to not split efforts and grow the community around an official repo.

Would love feedback and any comments or thoughts on the subject.

**Comment by mvanholsteijn** [comment]
Hi @LaikaN57 ,


The https://github.com/aws-cloudformation/custom-resource-helper is purely aimed at writing a lambda per custom resource. I wanted an object oriented programming model which supports multiple custom resources to be processed by a single lambda.

The aws-cloudformation/custom-resource-helper does not come with warranty or support from AWS, so I see no direct benefit of changing to the function based model.

Cheers,

Mark

**Comment by LaikaN57** [comment]
Fair enough. Just thought I would raise.

**Comment by mvanholsteijn** [comment]
Thank you for raising it. Out of curiosity, are you switching over? if so, how many custom providers did you write?

**Comment by LaikaN57** [comment]
Not looking at switching for now as this project suffices our needs. Looks like we have about 20-25 instances (and continuing to upgrade older code). We mostly use a 1:1 model of lambdas to providers.
