### ISSUE TITLE
Schema validation error gives "Response object is too long."

### ISSUE THREAD

**Issue by spockNinja** [binxio/cfn-resource-provider#2]
Thanks for this library! We're using it quite heavily for our DevOps solution, and it has been working really well.

I just ran into a case where a resource failed the schema validation, but the CloudFormation console simply shows "Response object is too long." as the error message.

I think sending the entire schema where the validation failed might be too much. If we just cut off the  error message a little earlier, that would be great.

I just looked at where that message is coming from, and it appears to be a simple `str(e)` on the validation error, which resolves to [this big message](https://github.com/Julian/jsonschema/blob/master/jsonschema/exceptions.py#L59). My suggested fix would be to catch the [ValidationError](https://python-jsonschema.readthedocs.io/en/latest/errors/#jsonschema.exceptions.ValidationError) and only pass along the `message` attribute.

If that sounds good, I would be happy to whip up a PR. Thanks!

**Comment by spockNinja** [comment]
@mvanholsteijn Wonderful! Thanks for the speedy response. 😄

**Comment by mvanholsteijn** [comment]
You are welcome. Glad that you find it useful!

Cheers, Mark
