### ISSUE TITLE
Strings starting with one or multiple 0's are converted to integers 

### ISSUE THREAD

**Issue by wvanheerde** [binxio/cfn-resource-provider#4]
Hiya,

First of all, thanks for a great library! I just ran into an issue where having a tag on a resource with value '00000014' was identified as an integer and then casted to int 14. Updating the resource is then not allowed because tags require a string value. We use those kind of padded values to map resources to internal order numbers of a fixed length.

Would it be possible to change the is_int() function to not detect those kind of values as an integer by - for example - making an exception on strings that have a length > 1 and start with a '0'?

Thanks,
Wessel

**Comment by mvanholsteijn** [comment]
By default CloudFormation sends all values as strings and by default the resource provider does not do any conversion.  You can implement specific type conversions for your field values by overriding the method `convert_property_types`.  This method is called before the request is validated against your json schema. 

The best generic converter  could  the json schema definition and only convert field types if they are not 'string'. I have not found a way to navigate the schema though.

For your case, I suggest you override  `convert_property_types` and only convert the fields you need. The nice thing is, if you they do not convert, you can leave them and the json schema validator will catch them for you. 

hope this helps...
