### ISSUE TITLE
convert_property_types behavior

### ISSUE THREAD

**Issue by ambsw-technology** [binxio/cfn-resource-provider#6]
`request_schema` already defines property types.  Why isn't that definition used for property conversion (where an exception in the conversion is a schema failure)?  I'm not even sure it even makes sense to keep the heuristic for nested values.  It seems like it would be better to explicitly support the [official](https://aws.amazon.com/blogs/devops/using-the-new-cloudformation-parameter-types/) nested parameter types:

```
List<Number> – An array of integers or floats
CommaDelimitedList – An array of literal strings that are separated by commas
List<AWS::EC2::VPC::Id> – An array of VPC IDs
List<AWS::EC2::SecurityGroup::Id> – An array of security group IDs
List<AWS::EC2::Subnet::Id> – An array of subnet IDs
```

If it isn't already happening, it could make sense to validate the complex string-types as well (both top-level and nested):

```
AWS::EC2::KeyPair::KeyName – An Amazon EC2 key pair name
AWS::EC2::SecurityGroup::Id – A security group ID
AWS::EC2::Subnet::Id – A subnet ID
AWS::EC2::VPC::Id – A VPC ID
```

You can default a bare `list` to either number or string but probably shouldn't be heuristically matching mixed content.

**Comment by mvanholsteijn** [comment]
Although CloudFormation allows you to use specific type literals for boolean and integers. It passes them all in to the custom provider as strings. 

The JSON schema of the provider specifies which type it expects and will fail if you do *not* convert the string to the type you expect.

I have not found an easy way to traverse the JSON schema to perform these type conversions, which would be the best solution.  That is why I added the ducktape heuristic function to very literals, which will do most of the time. Explicitly converting yourself in the function is even bertter.

Of course, it would be even nicer if CFN did deliver every thing as string.

Although the official types are nice, I have not found a real value for them in custom providers. If you need to pass in a vpc id and you pass in something else, the resource creation will also fail, just at a different point.

**Comment by ambsw-technology** [comment]
It's it as easy as...

```
for k, v in self.request_schema['properties'].items():
    if k not in self.properties:
        pass
    if v['type'] == 'boolean'
        self.properties[k] = self.properties[k].lower() == 'true'
    ...
```

**Comment by mvanholsteijn** [comment]
I did not think of that. I was looking at the jsonschema interface to provide me with a traversal function. It would be an improvement over the current heuristic version :-) 

Currently, I have little time to implement it,  so when I am bored I will consider adding it. A PR is welcome!

**Comment by ambsw-technology** [comment]
(originally posted in wrong issue)

I'll get to it if it blocks me, but I'm having to spend my time on other "blocker" changes (that I can PR).  For example, I develop in Windows so I have to run `make test` in a docker container already.  Having the raw `make` try to create another docker container is messy (not impossible, just messy) so I separated the make logic from the containerization so it *can* (though is not automatically) run in the host.
