### ISSUE TITLE
Built-in Polling

### ISSUE THREAD

**Issue by ambsw-technology** [binxio/cfn-resource-provider#7]
I need to support an async call to register a Directory Service with Workspaces.  Unlike `cfn-certificate-provider`, I don't need to do anything "in between" -- just wait for completion -- so I don't need a separate "wait" resource.  It would be great if this library had something like the [automatic polling methods](https://github.com/aws-cloudformation/custom-resource-helper/blob/master/crhelper/resource_helper.py#L188) found in `aws-cloudformation/custom-resource-helper`.  Another polling pattern can be found at [`cfn-lambda-handler`](https://github.com/mixja/cfn-lambda-handler) with some documentation about using stack status for rollback detection.

If it doesn't take longer than the Lambda timeout, I assume the half solution is to loop and sleep inside the create/delete methods.

**Comment by mvanholsteijn** [comment]
The resource provider does allow you to set 'self.asynchronous' to False, in which case the response is not send. You do have to  make sure that you get called again. 

I  solved this by introducing a specific custom resource which only has to poll for the condition to become true, and before the timeout expires,  the service calls itself again.  check out https://github.com/binxio/cfn-certificate-provider/blob/master/src/issued_certificate_provider.py

**Comment by ambsw-technology** [comment]
Great!  Then I'd propose porting those methods into this package so it's reusable.

You actually need a separate polling resource in `cfn-certificate-provider` because CF needs to take action (create the DNS entry) between the time you create the certificate request and the time the certificate is available for use.  I just need the one resource to wait until the resource is ready.
