### ISSUE TITLE
Response object is too long

### ISSUE THREAD

**Issue by ambsw-technology** [binxio/cfn-resource-provider#8]
I had an exception in my jsonschema (used `list` vs. `array`) which result in the following error:

![image](https://user-images.githubusercontent.com/8583181/87215274-865bd800-c2fa-11ea-8e92-f94f04b238ea.png)

I'm not sure if I can tell exactly what the response was, but it looks like it included the entire JSON Schema:

![image](https://user-images.githubusercontent.com/8583181/87215287-d5a20880-c2fa-11ea-9ce0-5c857e103698.png)

The error handling could probably be improved to avoid this issue e.g.. by catching `jsonschema.exceptions.UnknownType` explicitly.

**Comment by mvanholsteijn** [comment]
Hi @ambsw-technology, in 1.0.7, when the reason is longer than 200 characters, it is now truncated and '...' is added to indicate the truncation. Hope this helps.

Thanks your for feedback.
