### ISSUE TITLE
Preserve Error Class

### ISSUE THREAD

**Issue by ambsw-technology** [binxio/cfn-resource-provider#9]
I had a `KeyError` in my code.  It resulted in the following ambiguous line:

![image](https://user-images.githubusercontent.com/8583181/87237153-4d823880-c3b8-11ea-9e7d-29e55f2e5665.png)

I had a pretty good idea what was going on, but it's certainly possible that this won't be the case in other places.  For example, something trivial like "DirectoryId" would be hard to understand.  It would have been far more clear if `(KeyError)` was included somewhere in the error handling.

**Comment by mvanholsteijn** [comment]
Hi @ambsw-technology , in release 1.0.7 I have used traceback to render the error message and log the stacktrace.

Thanks for your feedback!
